/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_speech_restapi_jniTest_FileCutUtil */

#ifndef _Included_com_baidu_speech_restapi_jniTest_FileCutUtil
#define _Included_com_baidu_speech_restapi_jniTest_FileCutUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_speech_restapi_jniTest_FileCutUtil
 * Method:    setFile
 * Signature: ([C[C[C)I
 */
JNIEXPORT jint JNICALL Java_com_baidu_speech_restapi_jniTest_FileCutUtil_setFile
  (JNIEnv *, jobject, jcharArray, jcharArray, jcharArray);

/*
 * Class:     com_baidu_speech_restapi_jniTest_FileCutUtil
 * Method:    finalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_baidu_speech_restapi_jniTest_FileCutUtil_finalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
